base_dir: logs
data:
  batch_size: 32
  data_name: so_trunc_32
  data_filename: data/data_so_trunc_32/{}.pkl
  process_dim: 22
  use_cache: False
  cache_dir: cache
  # list of the names of the metrics.
  metrics: [type_acc, time_rmse]

model:
  name: AEHN
  # the number of events
  process_dim: 22
  hidden_dim: 32
  # hybrid or loglikelihood
  pred_method: loglikelihood

  # following three setting are activated when using loglikelihood
  n_loss_integral_sample: 80
  n_pred_integral_sample: 80
  max_time_pred: 2.0


train:
  dropout_rate: 0.0
  lr: 0.001
  epoch: 0
  max_epoch: 200
  lr_scheduler: PlateauLRScheduler
  patience: 15